<a href="https://colab.research.google.com/github/maro000/for_data_analysis_and_visualization/blob/master/function_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
A = np.random.randn(10)

In [9]:
A

array([ 0.20484561, -0.60875189,  0.5600843 ,  0.2509249 ,  0.02749815,
        0.46818532, -0.25391041,  0.5707617 , -1.2097519 , -0.17007541])

In [0]:
 B = np.random.randn(10)

In [11]:
B

array([-0.25811297, -0.4002486 ,  0.61894349, -1.54692348, -0.09195224,
        0.01270667, -0.41950268,  0.61940949, -0.58706261,  0.75579727])

In [12]:
np.add(A,B)

array([-0.05326736, -1.00900049,  1.17902779, -1.29599859, -0.06445409,
        0.48089199, -0.67341309,  1.19017119, -1.79681451,  0.58572186])

In [13]:
np.maximum(A,B)

array([ 0.20484561, -0.4002486 ,  0.61894349,  0.2509249 ,  0.02749815,
        0.46818532, -0.25391041,  0.61940949, -0.58706261,  0.75579727])