<a href="https://colab.research.google.com/github/maro000/for_data_analysis_and_visualization/blob/master/use_array_in_cal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
5/2

2.5

In [0]:
from __future__ import division

In [0]:
arr1 =np.array([[1,2,3,4],[8,9,10,11]])

In [6]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [7]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [10]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [0]:
arr =np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[8]

8

In [15]:
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[0:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_arr =arr[0:6]

In [24]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
slice_arr[:] = 99

In [26]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy =arr.copy()

In [29]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy[:] =50

In [31]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_2d =np.array ([[5,10,15],[20,25,30],[35,40,45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[1]

array([20, 25, 30])

In [37]:
arr_2d[1][0]

20

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[2]

array([35, 40, 45])

In [42]:
arr_2d[2,:]

array([35, 40, 45])

In [43]:
arr2d =np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
arr_length = arr2d.shape[1]

In [0]:
for i in range(arr_length):
  arr2d[i] =i 

In [47]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [48]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [49]:
arr2d[[5,2,1,3]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])