<a href="https://colab.research.google.com/github/maro000/for_data_analysis_and_visualization/blob/master/import_and_export_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
arr =np.arange(5)

In [2]:
arr

array([0, 1, 2, 3, 4])

In [0]:
np.save('my_array',arr)

In [0]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr1 =  np.load('my_array.npy')

In [0]:
arr2 =np.arange(10)

In [9]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1

array([0, 1, 2, 3, 4])

In [0]:
np.savez('ziparrays.npz', x = arr1, y=arr2)

In [0]:
archive_array =np.load('ziparrays.npz')

In [16]:
archive_array

In [17]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [0]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [19]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
np.savetxt('my_test_text.txt', arr,delimiter =',')

In [22]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00


In [0]:
arr = np.loadtxt('my_test_text.txt', delimiter =',')

In [24]:
arr

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])