<a href="https://colab.research.google.com/github/maro000/for_data_analysis_and_visualization/blob/master/make_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)

In [15]:
my_array1

array([1, 2, 3, 4])

In [0]:
my_list2 = [11,22,33,44]
my_lists =[my_list1, my_list2]

In [19]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [21]:
my_array2 =np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [22]:
my_array2.shape

(2, 4)

In [23]:
my_array2.dtype

dtype('int64')

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [0]:
 my_zeros = np.zeros(5)

In [27]:
my_zeros.dtype

dtype('float64')

In [28]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.empty((3,4))

array([[3.63855870e-316, 2.51973479e-322, 0.00000000e+000,
        0.00000000e+000],
       [2.46151512e-312, 1.16095484e-028, 7.52736939e+252,
        2.86750350e+161],
       [1.44506353e+214, 2.28176682e+243, 9.96124223e-143,
        4.05449735e-317]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])