<a href="https://colab.research.google.com/github/maro000/for_data_analysis_and_visualization/blob/master/Permutation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
dframe = DataFrame(np.arange(4*4).reshape((4,4)))

In [3]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [0]:
blender = np.array([0,3,2,1])

In [5]:
dframe.take(blender)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [0]:
blender = np.random.permutation(4)

In [10]:
blender

array([3, 1, 0, 2])

In [0]:
box = np.array(['A','B','C'])

In [12]:
box

array(['A', 'B', 'C'], dtype='<U1')

In [0]:
shaker = np.random.randint( 0, len(box), size =10)

In [14]:
shaker

array([1, 0, 1, 2, 0, 1, 2, 1, 0, 1])

In [15]:
shaker

array([1, 0, 1, 2, 0, 1, 2, 1, 0, 1])

In [0]:
hand_grabs = box.take(shaker)

In [18]:
hand_grabs

array(['A', 'B', 'B', 'A', 'C', 'B', 'B', 'A', 'A', 'C'], dtype='<U1')